### ISSUE TITLE
Fixed: Is this still working in CSS? [Yes]

### ISSUE THREAD

**Issue by ClaudiuHKS** [idk1703/TickrateEnabler#1]
Is this still working in CSS?
_NVM, fixed._

**Comment by ClaudiuHKS** [comment]
@ hi.

I have the CSS game server running.
If I have Windows Explorer, Google Chrome, Microsoft Edge or ANY OTHER application running in Full-Screen,
CSS server goes from 100 fps & 100 tick to 66 fps & 100 tick.
If I make the application windowed (Windows Explorer, Google Chrome, Microsoft Edge, Notepad, ...),
CSS server goes again 100 fps & 100 tick.
Do you have any idea or fix? Thanks.
Everything is running updated & latest versions available.

![image](https://user-images.githubusercontent.com/9334579/208161313-551282e0-95ac-41a8-aa48-39ec15191f69.png)

**Comment by idk1703** [comment]
> Is this still working in CSS?

Yes.



> @fuckOff1703 hi.
> 
> I have the CSS game server running. If I have Windows Explorer, Google Chrome, Microsoft Edge or ANY OTHER application running in Full-Screen, CSS server goes from 100 fps & 100 tick to 66 fps & 100 tick. If I make the application windowed (Windows Explorer, Google Chrome, Microsoft Edge, Notepad, ...), CSS server goes again 100 fps & 100 tick. Do you have any idea or fix? Thanks. Everything is running updated & latest versions available.
> 
> ![image](https://user-images.githubusercontent.com/9334579/208161313-551282e0-95ac-41a8-aa48-39ec15191f69.png)

Hi, how to reproduce this ? For example i launch css server with 100 tick and open css (fullscreen) and alt+tab, i see 100 fps on server.

**Comment by ClaudiuHKS** [comment]
@ to reproduce: https : // .................. / cssfps . mp4 (watch video in the browser)
_link removed_

**Comment by idk1703** [comment]
I can't reproduce this, not have win11, idk, try add high priority and test.

start.bat - `start /high /wait srcds.exe -console -game cstrike ...`

**Comment by ClaudiuHKS** [comment]
@idk1703 fixed it!

It happened in `hlds.exe` (**CS**) and `srcds.exe` (**CS:GO**) as well.

```C++
bool ::MmPlug::Load(::PluginId id, ::ISmmAPI* ismm, char* error, unsigned int maxlen, bool) noexcept
{
    ::ShowWindow(::GetActiveWindow(), { }); // 0 = { } = SW_HIDE
    // ::ShowWindow(::GetForegroundWindow(), { }); // 0 = { } = SW_HIDE
}
```

I just have now to use **RCON** `HLSW`. Not a huge problem for me.
Thank you for pointing me out that `Windows` is the problem, not `Valve`.
